export type ItemChecklist = {
  clausula: string
  requisito: string
  documento_referencia: string
  evidencia_sugerida: string
}

export const CHECKLIST_ISO_9001: ItemChecklist[] = [
  { clausula: '4.1', requisito: '¿La organización identifica las cuestiones externas e internas (FODA/PESTEL, incluido cambio climático) que afectan al SGI, y les da seguimiento y revisión periódica?', documento_referencia: 'Contexto de la Organización FDI-01', evidencia_sugerida: 'Documento FDI-01 vigente; evidencia de última revisión y responsable; PESTEL con cambio climático incluido.' },
  { clausula: '4.2', requisito: '¿Se determinan las partes interesadas pertinentes y sus requisitos, dando seguimiento a cambios?', documento_referencia: 'FDI-01', evidencia_sugerida: 'Matriz de partes interesadas dentro de FDI-01; evidencia de actualización ligada a 6.1/FSG-14.' },
  { clausula: '4.3', requisito: '¿El alcance está documentado, disponible y justifica exclusiones de la norma?', documento_referencia: 'FDI-01 / MSG-01 Manual de Gestión v01', evidencia_sugerida: 'Declaración de alcance; justificación de exclusiones si existen.' },
  { clausula: '4.4', requisito: '¿Están definidos los procesos con entradas, salidas, secuencia, interacción, criterios/indicadores, recursos y responsables (cláusula 4.4.1)?', documento_referencia: 'Mapa de Procesos DESG-01 v02; Tablero de indicadores FSG-06; Organigrama DEDI-01 v01', evidencia_sugerida: 'DESG-01 con las 11 fichas de proceso completas; evidencia de indicadores de al menos un proceso.' },
  { clausula: '5.1', requisito: '¿La alta dirección demuestra liderazgo: rinde cuentas de la eficacia del SGI, asegura política y objetivos compatibles con el contexto, promueve el enfoque a procesos y riesgos, y apoya a los responsables de área?', documento_referencia: 'MSG-01 v01; Política de Calidad e Inocuidad DEDI-02 v01', evidencia_sugerida: 'Evidencia de participación de dirección en revisiones y comunicación de la política.' },
  { clausula: '5.2', requisito: '¿La política es adecuada al propósito de la organización, comunicada y disponible para las partes interesadas?', documento_referencia: 'DEDI-02 v01', evidencia_sugerida: 'Política firmada; evidencia de difusión (inducción, carteles, firma de enterado).' },
  { clausula: '5.3', requisito: '¿Están asignadas, comunicadas y entendidas las responsabilidades y autoridades en la organización?', documento_referencia: 'Organigrama DEDI-01 v01; Descriptivos de puesto DRH-01 a DRH-24', evidencia_sugerida: 'Organigrama actualizado; descriptivos de puesto firmados por el colaborador.' },
  { clausula: '6.1', requisito: '¿Se determinan y abordan los riesgos/oportunidades derivados del contexto, partes interesadas y procesos? ¿La valoración refleja los controles ya existentes?', documento_referencia: 'PSG-05 v01; FSG-14 (Análisis de Riesgos y Oportunidades)', evidencia_sugerida: 'FSG-14 con trazabilidad a 4.1/4.2/4.3; planes de acción para riesgos Altos.' },
  { clausula: '6.2', requisito: '¿Existen objetivos medibles y coherentes con la política, con planes de acción, responsables, plazos y seguimiento?', documento_referencia: 'MSG-01; Tablero de indicadores FSG-06', evidencia_sugerida: 'Objetivos documentados; evidencia de seguimiento y resultados de indicadores.' },
  { clausula: '6.3', requisito: '¿Los cambios al SGI se planifican considerando su propósito, integridad del sistema, disponibilidad de recursos y asignación de responsabilidades?', documento_referencia: 'PSG-13 v01 (Gestión de Cambios)', evidencia_sugerida: 'Registros de solicitudes y aprobación de cambios.' },
  { clausula: '7.1', requisito: '¿Se determinan y proveen los recursos necesarios? ¿Los equipos de medición están calibrados/verificados?', documento_referencia: 'MSG-01; PMT-01 v01; MTI-01 v02', evidencia_sugerida: 'Programa de mantenimiento; inventario y evidencia de calibración de equipos de medición.' },
  { clausula: '7.2', requisito: '¿Se determina la competencia necesaria del personal, se capacita y se conservan registros de eficacia?', documento_referencia: 'PRH-01 v03; PRH-03 v03; Descriptivos DRH-XX', evidencia_sugerida: 'Matriz/programa de capacitación; expedientes de personal; evaluaciones de conocimientos.' },
  { clausula: '7.3', requisito: '¿El personal conoce la política, los objetivos, su contribución al SGI y las implicaciones de no conformidad?', documento_referencia: 'PRH-01 v03; DESG-02 v01', evidencia_sugerida: 'Evidencia de inducción y capacitación en política/objetivos.' },
  { clausula: '7.4', requisito: '¿Existe un proceso de comunicación interna y externa definido (qué, cuándo, a quién, cómo, quién)?', documento_referencia: 'Matriz de Comunicación DESG-03 v01', evidencia_sugerida: 'DESG-03 actualizada; evidencia de comunicaciones registradas.' },
  { clausula: '7.5', requisito: '¿Se controla la creación, actualización, aprobación, distribución y conservación de documentos y registros? ¿La lista maestra está libre de inconsistencias?', documento_referencia: 'PSG-01 v01; FSG-01; MSG-06 v01', evidencia_sugerida: 'FSG-01 sin duplicados ni inconsistencias; documentos con código, versión y fecha visibles.' },
  { clausula: '8.1', requisito: '¿Se planifican y controlan los procesos operativos conforme a criterios definidos y se conservan registros?', documento_referencia: 'DESG-01; procedimientos PBAL y PKTL', evidencia_sugerida: 'Evidencia de cumplimiento de criterios de proceso en piso.' },
  { clausula: '8.2', requisito: '¿Se determinan y revisan los requisitos del cliente antes de comprometerse contractualmente?', documento_referencia: 'PCV-01 v03', evidencia_sugerida: 'Contratos/cotizaciones revisados; registro de cambios de requisitos del cliente.' },
  { clausula: '8.4', requisito: '¿Se evalúan, seleccionan y controlan los proveedores críticos y procesos externos?', documento_referencia: 'PCO-01 v02; PCO-02 v02; PBAL-06 v01', evidencia_sugerida: 'Evaluaciones de proveedores críticos; criterios de selección; fichas técnicas FSG-18.' },
  { clausula: '8.5', requisito: '¿Las operaciones de almacenaje/transporte se realizan bajo condiciones controladas (identificación, trazabilidad, propiedad del cliente, preservación)?', documento_referencia: 'PBAL-01/02/04/05; PKTL-01/02', evidencia_sugerida: 'Registros de recepción, ubicación, conteos cíclicos y embarque.' },
  { clausula: '8.6', requisito: '¿Se verifica el cumplimiento de requisitos antes de liberar/despachar producto?', documento_referencia: 'PBAL-05 v05', evidencia_sugerida: 'Registros de liberación/despacho autorizados por personal competente.' },
  { clausula: '8.7', requisito: '¿Se identifican, controlan, documentan y disponen las salidas no conformes?', documento_referencia: 'PSG-02 v02', evidencia_sugerida: 'Registro de Control de producto no conforme FSG-11.' },
  { clausula: '9.1', requisito: '¿Se mide la satisfacción del cliente y el desempeño de los procesos mediante indicadores?', documento_referencia: 'MSG-01; Tablero de indicadores FSG-06', evidencia_sugerida: 'Resultados de indicadores; evidencia de encuestas o retroalimentación de clientes.' },
  { clausula: '9.2', requisito: '¿Existe programa anual de auditorías, se ejecuta conforme a lo planificado y se documentan hallazgos, informes y planes de reacción?', documento_referencia: 'PSG-06 v02', evidencia_sugerida: 'Programa anual FSG-54; Plan FSG-56; Lista de verificación FSG-57; Informe FSG-58; Lista de asistencia FSG-02.' },
  { clausula: '9.3', requisito: '¿La dirección revisa el SGI a intervalos planificados considerando todas las entradas de la norma (9.3.2)?', documento_referencia: 'PDI-01 v02', evidencia_sugerida: 'Minutas de revisión por la dirección; seguimiento a acuerdos y pendientes previos.' },
  { clausula: '10.1/10.2', requisito: '¿Se reacciona ante no conformidades, se analiza la causa raíz, se implementan acciones y se verifica su eficacia?', documento_referencia: 'PSG-04 v01', evidencia_sugerida: 'Registro de acción correctiva y preventiva FSG-09; evidencia de cierre y verificación de eficacia.' },
  { clausula: '10.3', requisito: '¿Existe evidencia de mejora continua derivada del análisis de indicadores y de la revisión por la dirección?', documento_referencia: 'MSG-01; FSG-06; PDI-01 v02', evidencia_sugerida: 'Acciones de mejora documentadas y su seguimiento.' },
]

export const CHECKLIST_SQF: ItemChecklist[] = [
  { clausula: '2.1.1', requisito: '¿Existe una declaración de política que incluya el compromiso de suministrar alimentos inocuos y establecer una cultura de inocuidad alimentaria?', documento_referencia: 'MSG-03 v02; Política de Calidad e Inocuidad DEDI-02 v01', evidencia_sugerida: 'Política firmada, difundida y con evidencia de medición de cultura de inocuidad alimentaria.' },
  { clausula: '2.1.2', requisito: '¿La alta gerencia revisa el Sistema SQF al menos una vez al año y mantiene informada mensualmente a la gerencia sobre asuntos que afecten su implementación?', documento_referencia: 'PDI-01 v02', evidencia_sugerida: 'Minuta anual de revisión; Tablero FSG-06; Minuta mensual FSG-08.' },
  { clausula: '2.1.3', requisito: '¿Se documentan e implementan métodos para manejar, investigar y resolver quejas de inocuidad alimentaria de clientes y autoridades?', documento_referencia: 'PSG-03 v02; PSG-04 v01', evidencia_sugerida: 'Registro de quejas y su análisis de causa raíz cuando aplique.' },
  { clausula: '2.2.2', requisito: '¿Se mantiene el control de documentos vigentes, con acceso del personal a instrucciones actualizadas?', documento_referencia: 'PSG-01 v01; FSG-01', evidencia_sugerida: 'FSG-01 sin errores, sin duplicados, sin documentos activos sin datos.' },
  { clausula: '2.2.3', requisito: '¿Los registros son legibles, están firmados por quien realiza el monitoreo, son accesibles, recuperables y protegidos, con tiempos de resguardo definidos?', documento_referencia: 'PSG-01 v01', evidencia_sugerida: 'Muestra de registros firmados; tabla de control de registros con tiempos de resguardo.' },
  { clausula: '2.3.1', requisito: '¿Están documentados y aprobados por el cliente los requisitos de manipulación/almacenamiento de cada producto?', documento_referencia: 'PCV-01 v03; FSG-17', evidencia_sugerida: 'FSG-17 por tipo de producto (alimento humano, cacahuate, alimento balanceado, electrónicos, vidrio).' },
  { clausula: '2.3.2', requisito: '¿Se documentan métodos para el desarrollo y aprobación de proveedores?', documento_referencia: 'PCO-01 v02; PCO-02 v02', evidencia_sugerida: 'Listado de proveedores aprobados; evidencia de evaluación.' },
  { clausula: '2.3.3', requisito: '¿Se controlan los proveedores de servicios subcontratados (transporte externo, plagas, mantenimiento)?', documento_referencia: 'PCO-01 v02; PCO-02 v02; PBAL-06 v01', evidencia_sugerida: 'Ficha técnica de proveedores de servicio FSG-18.' },
  { clausula: '2.3.4', requisito: '¿Se documentan y revisan los acuerdos contractuales con almacenes/transportistas externos, conservando registros de cambios y aprobaciones?', documento_referencia: 'PCO-01/02; PBAL-06; PKTL-01/02', evidencia_sugerida: 'Contratos vigentes; registros de revisión.' },
  { clausula: '2.4.1', requisito: '¿Se garantiza el cumplimiento de la legislación aplicable y se notifica al SQFI en 24 horas ante advertencia regulatoria?', documento_referencia: 'FSG-19; FSG-07', evidencia_sugerida: 'Matriz legal actualizada; evidencia de notificación si hubo evento.' },
  { clausula: '2.4.2', requisito: '¿Las BPA/BPD del Módulo 12 se aplican o se excluyen con un análisis de riesgo documentado que justifique la exención?', documento_referencia: 'MSG-02 v02', evidencia_sugerida: 'Análisis de riesgo para cada exclusión (NA) declarada, p. ej. cadena de frío.' },
  { clausula: '2.4.3', requisito: '¿Existe un Plan HACCP con equipo formado, descripción de producto, uso previsto, diagrama de flujo, análisis de peligros y PCC?', documento_referencia: 'PSG-14 v01', evidencia_sugerida: 'Formato Equipo HACCP-29; diagrama de flujo validado; registros de monitoreo de PCC si existen.' },
  { clausula: '2.4.4', requisito: '¿Se pone en cuarentena, identifica y dispone el producto/equipo no conforme de forma que reduzca el riesgo?', documento_referencia: 'PSG-02 v02', evidencia_sugerida: 'Registro de cuarentena; Control de producto no conforme FSG-11.' },
  { clausula: '2.4.5', requisito: '¿Las operaciones de recuperación garantizan trazabilidad y las realiza personal capacitado?', documento_referencia: 'PSG-02 v02', evidencia_sugerida: 'Registros de recuperación de producto.' },
  { clausula: '2.4.6', requisito: '¿El despacho lo autoriza personal designado y se mantienen registros de todo lo despachado?', documento_referencia: 'PBAL-05 v05', evidencia_sugerida: 'Registros de embarque con firma de autorización.' },
  { clausula: '2.5.1', requisito: '¿Se ratifican las BPA/BPD y se revalidan anualmente los límites críticos de inocuidad?', documento_referencia: 'PSG-15 v01', evidencia_sugerida: 'Registros de validación anual.' },
  { clausula: '2.5.2', requisito: '¿Existe cronograma de verificación con responsables y frecuencia, con registros de verificación?', documento_referencia: 'PSG-16 v02', evidencia_sugerida: 'Cronograma FSG-43; registros firmados.' },
  { clausula: '2.5.3', requisito: '¿Se documenta la causa raíz, la implementación y la verificación de eficacia de las acciones correctivas/preventivas?', documento_referencia: 'PSG-04 v01', evidencia_sugerida: 'Registro FSG-09.' },
  { clausula: '2.5.4', requisito: '¿Se realizan auditorías internas completas al menos una vez al año, con evidencia objetiva, acciones correctivas y comunicación de resultados?', documento_referencia: 'PSG-06 v02; PSG-16 v02', evidencia_sugerida: 'Programa anual FSG-54; evidencia de competencia de auditores; Evaluación FSG-60.' },
  { clausula: '2.6.1', requisito: '¿El sistema de identificación asegura rotación adecuada de existencias en todas las etapas de almacenamiento?', documento_referencia: 'PBAL-01 v06; PBAL-02 v01', evidencia_sugerida: 'Evidencia de rotación FIFO/FEFO; etiquetado de lote.' },
  { clausula: '2.6.2', requisito: '¿Se puede trazar el producto un paso adelante y un paso atrás, incluido un simulacro de trazabilidad documentado?', documento_referencia: 'MSG-07 v01', evidencia_sugerida: 'Registro de simulacro de trazabilidad reciente (tiempo y % de recuperación).' },
  { clausula: '2.6.3 ⚠ CRÍTICO', requisito: '¿El procedimiento de retirada incluye la notificación obligatoria al SQFI en 24 horas a foodsafetycrisis@sqfi.com? ¿Incluye simulacro anual de retirada?', documento_referencia: 'PSG-17 v01', evidencia_sugerida: 'Texto de PSG-17 con la notificación de 24h; registro de simulacro de retirada.' },
  { clausula: '2.6.4', requisito: '¿Existe un plan de gestión de crisis con equipo, roles y protocolos de actuación?', documento_referencia: 'MSG-12 v01', evidencia_sugerida: 'Integración de brigada de emergencia; evidencia de simulacros.' },
  { clausula: '2.7.1', requisito: '¿Existe una evaluación de vulnerabilidad y un plan de defensa alimentaria implementado?', documento_referencia: 'MSG-04 v01', evidencia_sugerida: 'Evaluación de vulnerabilidad; medidas de mitigación implementadas.' },
  { clausula: '2.7.2', requisito: '¿Existe una evaluación de vulnerabilidad a fraude alimentario y un plan de mitigación?', documento_referencia: 'MSG-05 v01', evidencia_sugerida: 'Evaluación de vulnerabilidad a fraude; plan de mitigación por producto/proveedor.' },
  { clausula: '2.8.1', requisito: '¿Se identifican, controlan y previenen la contaminación cruzada de alérgenos declarados (cacahuate)? ¿El etiquetado y la separación física son adecuados?', documento_referencia: 'PSG-21 v01', evidencia_sugerida: 'Separación física del cacahuate; verificación de etiquetado; registros de limpieza entre manejo de alérgenos.' },
  { clausula: '2.9.1/2.9.2', requisito: '¿Existe un programa de capacitación en inocuidad alimentaria, higiene y BPA/BPD, con evaluación de conocimientos adquiridos?', documento_referencia: 'PRH-01 v03', evidencia_sugerida: 'Matriz/programa de capacitación; evaluaciones FRH-17; expedientes de personal.' },
  { clausula: '12.1.1', requisito: '¿Se cuenta con el Análisis de Riesgos Locales y del Entorno actualizado y los permisos de funcionamiento vigentes?', documento_referencia: 'FSG-20', evidencia_sugerida: 'FSG-20 actualizado; permisos de funcionamiento vigentes.' },
  { clausula: '12.1.3', requisito: '¿La iluminación es adecuada y los accesorios cuentan con protección para evitar contaminación por rotura?', documento_referencia: 'PSG-07 v01; PMT-01 v01', evidencia_sugerida: 'Inspección visual de protecciones en luminarias sobre áreas de producto.' },
  { clausula: '12.1.4', requisito: '¿Las instalaciones están protegidas contra el ingreso de plagas (sellos, cortinas, trampas)?', documento_referencia: 'MSG-09 v02', evidencia_sugerida: 'Layout de dispositivos de control de plagas; reportes del proveedor.' },
  { clausula: '12.1.5/6/7', requisito: '¿La ventilación evita condensación/contaminación? ¿Equipos y utensilios están en buen estado? ¿Terrenos y vías de acceso están libres de agua estancada y basura?', documento_referencia: 'PSG-07; PMT-01; ABAL-03', evidencia_sugerida: 'Recorrido físico de instalaciones y patios.' },
  { clausula: '12.2.1', requisito: '¿Existe programa de mantenimiento preventivo/correctivo que evite riesgos de contaminación (vidrio, fragmentos, lubricantes)?', documento_referencia: 'PMT-01 v01', evidencia_sugerida: 'Programa de mantenimiento; órdenes de trabajo cerradas.' },
  { clausula: '12.2.2', requisito: '¿Se controla el acceso y las actividades de contratistas para evitar contaminación?', documento_referencia: 'PSG-10 v02', evidencia_sugerida: 'Registro de ingreso y supervisión de contratistas.' },
  { clausula: '12.2.3', requisito: '¿Los equipos de medición críticos están calibrados/verificados con frecuencia definida?', documento_referencia: 'MTI-01 v02; PMT-01 v01', evidencia_sugerida: 'Certificados o registros de calibración/verificación.' },
  { clausula: '12.2.4', requisito: '¿Existe programa de control de plagas con proveedor certificado, mapa de dispositivos, análisis de tendencias y verificación de reportes?', documento_referencia: 'MSG-09 v02', evidencia_sugerida: 'Programa de control de plagas; análisis de tendencias; verificación de visitas FSG-62.' },
  { clausula: '12.2.5', requisito: '¿Existe programa de limpieza con métodos, frecuencia, verificación y registro? ¿Los insumos de limpieza están identificados y almacenados adecuadamente?', documento_referencia: 'PSG-07 v01', evidencia_sugerida: 'Programa de limpieza; registros de limpieza y verificación.' },
  { clausula: '12.3.1-4', requisito: '¿Se restringe el acceso a personal enfermo o con heridas expuestas? ¿Hay lavamanos suficientes? ¿Se controla el ingreso de visitantes?', documento_referencia: 'DESG-02 v01; PSG-10 v02', evidencia_sugerida: 'Recorrido a estaciones de lavado de manos; registro de ingreso de visitantes.' },
  { clausula: '12.3.5', requisito: '¿Los servicios sanitarios y salas de descanso están separados de las áreas de manipulación, limpios y con señalización de lavado de manos?', documento_referencia: 'ABAL-03; PSG-07; PMT-01; MSG-09; DESG-02', evidencia_sugerida: 'Recorrido físico a sanitarios y comedor.' },
  { clausula: '12.4.1', requisito: '¿Se cumplen las prácticas de higiene en piso (sin comer/fumar en área de producto, manejo adecuado de residuos, agua potable controlada)?', documento_referencia: 'DESG-02 v01', evidencia_sugerida: 'Observación directa en piso durante la auditoría.' },
  { clausula: '12.5.1/2', requisito: '¿El agua usada en limpieza proviene de fuente controlada, con análisis de calidad periódico y plan de contingencia ante contaminación?', documento_referencia: 'PSG-07 v01; MSG-11 v01', evidencia_sugerida: 'Análisis de laboratorio de calidad de agua; bitácora de limpieza de cisternas.' },
  { clausula: '12.6.1', requisito: '¿Se inspecciona la mercancía a la recepción (integridad, plagas, temperatura si aplica) y se ubica conforme a criterios definidos?', documento_referencia: 'PBAL-01 v06; PBAL-02 v01', evidencia_sugerida: 'Registros de inspección de recepción; evidencia de ubicación por zonas.' },
  { clausula: '12.6.2', requisito: '¿Aplica cadena de frío? Si no, ¿está documentada la exclusión (NA) con justificación?', documento_referencia: 'MSG-02 v02', evidencia_sugerida: 'Confirmar declaración NA vigente: no se maneja refrigeración/congelación.' },
  { clausula: '12.6.3', requisito: '¿Los productos secos están alejados de zonas húmedas y protegidos de plagas?', documento_referencia: 'PBAL-02 v01; MSG-09 v02', evidencia_sugerida: 'Recorrido físico a zonas de almacenaje de producto seco.' },
  { clausula: '12.6.4', requisito: '¿Los químicos están identificados, controlados y registrados para evitar contaminación de alimentos?', documento_referencia: 'MSG-08 v02', evidencia_sugerida: 'Registro actualizado de productos químicos usados en instalaciones.' },
  { clausula: '12.6.5', requisito: '¿La carga/descarga se realiza de forma que evite contaminación y se registra adecuadamente?', documento_referencia: 'PBAL-05 v05; PKTL-01/02', evidencia_sugerida: 'Checklist de inspección de unidades de transporte externo.' },
  { clausula: '12.7.1', requisito: '¿El flujo de personal y producto está diseñado para prevenir contaminación cruzada?', documento_referencia: 'PBAL-02 v01; ABAL-03', evidencia_sugerida: 'Layout actualizado; observación de flujo en piso.' },
  { clausula: '12.7.2/3', requisito: '¿Se controla el uso de vidrio/plástico quebradizo con inventario y protocolo ante rotura? ¿Hay checklist de integridad de nave?', documento_referencia: 'PSG-09 v01', evidencia_sugerida: 'Inventario de vidrio; checklist de limpieza e integridad de la nave FMT-04.' },
  { clausula: '12.8.1', requisito: '¿Los residuos se identifican, segregan, almacenan y disponen evitando contaminación y atracción de plagas?', documento_referencia: 'MSG-10 v03', evidencia_sugerida: 'Áreas de residuos identificadas; evidencia de disposición final.' },
]

export function checklistPorNorma(norma: string): ItemChecklist[] {
  if (norma === 'iso_9001') return CHECKLIST_ISO_9001
  if (norma === 'sqf') return CHECKLIST_SQF
  if (norma === 'ambas') return [...CHECKLIST_ISO_9001, ...CHECKLIST_SQF]
  return []
}
